### ISSUE TITLE
Petition to Remove "Sensitive Content" Warnings from Kris Nóva's Twitter content.

### ISSUE THREAD

**Issue by krisnova** [kris-nova/kris-nova#2]
This is a petition to remove the "Sensitive Content" warnings from [Kris Nóva](https://twitter.com/krisnova)'s Twitter account. 

For more information on the topic, please read the [Why Twitter Flags All My Content as "Sensitive"](https://medium.com/@kris-nova/why-twitter-flags-all-my-content-as-sensitive-6230738521f3) blog.

---

To show your support, and sign the petition please interact with this Github issue.

 - Add a 👍🏻 emoji to the issue
 - Add a small comment below with a brief explanation why this would be helpful for you
 - Share an anecdote about when the content warning was inappropriate
 - Share an anecdote about when the content warning was counter productive to something you were trying to accomplish 
 - Share an anecdote about when the content warning created an undesirable user experience for Twitter

**Comment by mihaitodor** [comment]
I have a hard time sharing content from Kris if recipients end up seeing a big warning labeling it as inappropriate, even though there's nothing inappropriate about it. This hinders the community growth and makes it difficult for us to keep in touch.

**Comment by finalcut** [comment]
I ask to see sensitive content and I have yet to see anything from this account that should have met the threshold of "Sensitive"; there is literally nothing offensive, rude, or misleading in what I've read on this account.

**Comment by ainghazal** [comment]
I was utterly confused by having that weird "sensitive content" alert. I just thought the AI takeover was more advanced than we'd like to think, or that twitter overlords are offended by either the word "hacking" being next to "capitalism".

Limiting our ability to follow updates by this account is damaging the whole cybersecurity & tech community, and lowering the value of being in such platform by degrading our user experience. 

OTOH, nothing surprising: twitter is just another case of centralized, corporate decision making posing as a public service. Quite contradicting the "free speech" discourse they like to defend on the surface. Arbitrarily limiting someone's ability to connect with their community on such unfounded basis is not fair, especially taking into account how viral other accounts are allowed to be.

**Comment by jasonbur** [comment]
In interacting with https://twitter.com/krisnova, I didn't see anything that would warrant being flagged as sensitive information, and this appears to be in error. 

This user is a trans woman, a group which often struggles with having their voices heard. Part of the problem is that technology systems overly sexualize their words, or misinterpret the meaning.

It's an accepted fact in computer science that when groups are underrepresented in developing systems, their needs are unlikely to be met. Companies like Twitter have an obligation to not only try hard to avoid situations like this, but to put rigorous review processes in place so aggrieved parties such as this user can be heard and their concerns addressed.

Please provide very clear rules about appealing what people call "shadow bans" so that those affected can try to get real relief through human interaction.

**Comment by pmbrent** [comment]
The sensitive content warning appeared over a link to a tweet from Twitter Support explaining the sensitive content appeals process. This is very confusing and counterintuitive design; I almost didn't click it, but the allegedly sensitive content was from a verified Twitter source.

**Comment by securingdev** [comment]
Signed. 

This is utter 🐂💩 and I'm sorry you're going through this Kris. Hang tough 🤙 I hope that there will be other avenues to follow your inspiring content.

- Keith // securingdev

**Comment by IsaacLeeWebDev** [comment]
Kris's content on Twitter is not sensitive content. The shadow ban on @krisnova on Twitter reduces public exposure to educational resources that make the internet a safer place, and is a disservice to the public.

**Comment by feloy** [comment]
I learned a lot in the Kubernetes area thanks to @kris-nova . Please make their content visible

**Comment by krisnova** [comment]
Closing this issue. Twitter was able to restore my account and is no longer flagging my content.

Thank you everyone for your support! You all helped make a difference in my life today.
